# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20160414_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='object_id',
            field=models.CharField(max_length=128),
        ),
    ]
