# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20160526_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.Cart', verbose_name='cart'),
        ),
    ]
