# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20160621_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
    ]
